# config/default.yml

php:
  supported_versions: ['7.4', '8.1', '8.2', '8.3', '8.4']
  default_version: '8.4'

apache:
  default_php_version: '8.2'
  doc_root_subdir: 'web'

mysql:
  default_charset: 'utf8mb4'
  default_collation: 'utf8mb4_unicode_ci'

drupal:
  default_profile: 'standard'
  default_version: '^10'
  # El path de composer y drush puede variar, se puede sobreescribir
  # en los archivos de config espec√≠ficos de cada OS.
  composer_path: 'composer'
  drush_path: 'drush'

security:
  require_sudo: True
  backup_before_changes: True
  dry_run_by_default: False
